import 'package:flutter/material.dart';

/// Hand-rolled localization (no codegen) for English + Hindi.
class AppLocalizations {
  AppLocalizations(this.locale);
  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const _strings = <String, Map<String, String>>{
    'en': {
      'app_title': 'Milk Delivery',
      'login_title': 'Sign in',
      'phone_hint': 'Phone number',
      'send_otp': 'Send OTP',
      'otp_hint': 'Enter OTP (123456)',
      'verify': 'Verify',
      'select_role': 'Continue as',
      'role_milkman': 'Milkman',
      'role_subscriber': 'Subscriber',
      'name_hint': 'Your name',
      'milkman_home': 'Today\'s Route',
      'societies': 'Societies',
      'inbox': 'Inbox',
      'billing': 'Billing',
      'add_society': 'Add Society',
      'society_name': 'Society name',
      'society_address': 'Address',
      'add_flat': 'Add Flat',
      'flat_number': 'Flat number',
      'owner_name': 'Owner name',
      'owner_phone': 'Owner phone',
      'has_app': 'Subscriber has the app',
      'default_quantity': 'Default daily quantity (L)',
      'price_per_litre': 'Price per litre',
      'delivered': 'Delivered',
      'skipped': 'Skipped',
      'paused': 'Paused',
      'custom': 'Custom',
      'mark_delivered': 'Mark Delivered',
      'mark_custom': 'Custom Qty',
      'mark_skipped': 'Skip',
      'change_qty_dialog': 'Quantity (litres)',
      'reason_optional': 'Reason (optional)',
      'save': 'Save',
      'cancel': 'Cancel',
      'whatsapp_notify': 'Notify via WhatsApp',
      'change_requests': 'Change Requests',
      'no_requests': 'No pending requests.',
      'apply': 'Apply',
      'subscriber_today': 'Today',
      'subscriber_history': 'History',
      'subscriber_bill': 'My Bill',
      'pause_today': 'Pause today',
      'pause_tomorrow': 'Pause tomorrow',
      'pause_range': 'Pause date range',
      'change_quantity': 'Change quantity',
      'litres': 'L',
      'total_litres': 'Total litres',
      'total_amount': 'Total amount',
      'days_skipped': 'Days skipped',
      'days_custom': 'Days with custom qty',
      'export_pdf': 'Export PDF',
      'share': 'Share',
      'audit_log': 'Audit log',
      'no_flats': 'No flats yet. Tap + to add one.',
      'no_societies': 'No societies yet. Tap + to add one.',
      'logout': 'Logout',
      'language': 'Language',
      'pending': 'Pending',
      'applied': 'Applied',
      'pause': 'Pause',
      'quantity_change': 'Quantity change',
      'from': 'From',
      'to': 'To',
      'select_dates': 'Select dates',
      'request_submitted': 'Request submitted',
      'no_history': 'No deliveries yet.',
      'monthly_summary': 'Monthly Summary',
      'flat_detail': 'Flat detail',
      'logged_in_as': 'Signed in as',
      'unlinked_subscriber': 'No flat is registered for your phone yet.',
      'unlinked_explainer':
          'Your milkman needs to add a flat with this phone number as the owner. Share the number below with them, then sign back in.',
      'your_phone': 'Your phone',
      'copy': 'Copy',
      'copied': 'Copied to clipboard',
      'try_demo': 'Or try a demo account',
      'demo_subscriber_hint':
          'Sign out and sign in with 9111111111 or 9222222222 (OTP 123456) — both have flats already linked.',
      'milkman_absent': 'Milkman absent',
      'milkman_off_today': 'You\'re off today',
      'im_off_today': 'I\'m off today',
      'manage_absences': 'Manage absences',
      'add_absence': 'Add absence',
      'absence_single_day': 'Single day',
      'absence_range': 'Date range',
      'absence_recurring': 'Weekly off',
      'select_day_of_week': 'Day of the week',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'no_absences': 'No absences scheduled.',
      'remove': 'Remove',
      'confirm_broadcast': 'Notify subscribers?',
      'broadcast_explainer':
          'App subscribers will see "no delivery" automatically. Tap below to send WhatsApp messages to subscribers without the app.',
      'broadcast_via_whatsapp': 'Notify all via WhatsApp',
      'skip_notifications': 'Skip notifications',
      'no_delivery_today': 'No delivery today — milkman off',
      'no_delivery_explainer':
          'Your milkman is off today. There will be no delivery and you won\'t be charged.',
      'absence_added': 'Absence saved',
      'every_week_on': 'Every',
      'days_milkman_absent': 'Days milkman absent',
      'days_subscriber_paused': 'Days subscriber paused',
      'days_delivered_label': 'Days delivered',
      'absent_today_banner_explainer':
          'Subscribers will see "no delivery today" and these dates won\'t be billed.',
      'undo_off_today': 'Undo',
      'absence_reason_hint': 'Reason (optional, e.g. festival, sick)',
      'today_label': 'Today',
      'yesterday_label': 'Yesterday',
      'no_deliveries_today': 'No deliveries scheduled for today.',
      'qty_label': 'Qty',
      'mark_all_done': 'Mark all default',
      'old': 'Old',
      'new': 'New',
      'by': 'By',
    },
    'hi': {
      'app_title': 'दूध डिलीवरी',
      'login_title': 'साइन इन करें',
      'phone_hint': 'फ़ोन नंबर',
      'send_otp': 'OTP भेजें',
      'otp_hint': 'OTP दर्ज करें (123456)',
      'verify': 'सत्यापित करें',
      'select_role': 'जारी रखें',
      'role_milkman': 'दूधवाला',
      'role_subscriber': 'ग्राहक',
      'name_hint': 'आपका नाम',
      'milkman_home': 'आज का रूट',
      'societies': 'सोसाइटी',
      'inbox': 'इनबॉक्स',
      'billing': 'बिल',
      'add_society': 'सोसाइटी जोड़ें',
      'society_name': 'सोसाइटी का नाम',
      'society_address': 'पता',
      'add_flat': 'फ्लैट जोड़ें',
      'flat_number': 'फ्लैट नंबर',
      'owner_name': 'मालिक का नाम',
      'owner_phone': 'मालिक का फ़ोन',
      'has_app': 'ग्राहक के पास ऐप है',
      'default_quantity': 'रोज़ की डिफ़ॉल्ट मात्रा (लीटर)',
      'price_per_litre': 'प्रति लीटर मूल्य',
      'delivered': 'डिलीवर हुआ',
      'skipped': 'छोड़ा गया',
      'paused': 'रुका हुआ',
      'custom': 'अलग मात्रा',
      'mark_delivered': 'डिलीवर्ड',
      'mark_custom': 'अलग मात्रा',
      'mark_skipped': 'छोड़ें',
      'change_qty_dialog': 'मात्रा (लीटर)',
      'reason_optional': 'कारण (वैकल्पिक)',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'whatsapp_notify': 'WhatsApp पर सूचित करें',
      'change_requests': 'बदलाव अनुरोध',
      'no_requests': 'कोई अनुरोध नहीं है।',
      'apply': 'लागू करें',
      'subscriber_today': 'आज',
      'subscriber_history': 'इतिहास',
      'subscriber_bill': 'मेरा बिल',
      'pause_today': 'आज रोकें',
      'pause_tomorrow': 'कल रोकें',
      'pause_range': 'तारीख़ रेंज में रोकें',
      'change_quantity': 'मात्रा बदलें',
      'litres': 'ली',
      'total_litres': 'कुल लीटर',
      'total_amount': 'कुल राशि',
      'days_skipped': 'छोड़े गए दिन',
      'days_custom': 'अलग मात्रा वाले दिन',
      'export_pdf': 'PDF एक्सपोर्ट',
      'share': 'शेयर',
      'audit_log': 'ऑडिट लॉग',
      'no_flats': 'अभी कोई फ्लैट नहीं। + दबाकर जोड़ें।',
      'no_societies': 'अभी कोई सोसाइटी नहीं। + दबाकर जोड़ें।',
      'logout': 'लॉगआउट',
      'language': 'भाषा',
      'pending': 'लंबित',
      'applied': 'लागू',
      'pause': 'रोकें',
      'quantity_change': 'मात्रा बदलाव',
      'from': 'से',
      'to': 'तक',
      'select_dates': 'तारीख़ चुनें',
      'request_submitted': 'अनुरोध भेजा गया',
      'no_history': 'अभी कोई डिलीवरी नहीं।',
      'monthly_summary': 'महीने का सारांश',
      'flat_detail': 'फ्लैट विवरण',
      'logged_in_as': 'साइन इन',
      'unlinked_subscriber': 'इस नंबर पर अभी कोई फ्लैट रजिस्टर नहीं है।',
      'unlinked_explainer':
          'आपके दूधवाले को इस फ़ोन नंबर के मालिक के रूप में फ्लैट जोड़ना होगा। नीचे का नंबर उन्हें दें, फिर दोबारा साइन इन करें।',
      'your_phone': 'आपका फ़ोन',
      'copy': 'कॉपी करें',
      'copied': 'क्लिपबोर्ड पर कॉपी हो गया',
      'try_demo': 'या डेमो अकाउंट आज़माएँ',
      'demo_subscriber_hint':
          'साइन आउट करके 9111111111 या 9222222222 (OTP 123456) से साइन इन करें — दोनों के फ्लैट पहले से लिंक हैं।',
      'milkman_absent': 'दूधवाला छुट्टी पर',
      'milkman_off_today': 'आज आप छुट्टी पर हैं',
      'im_off_today': 'आज मैं छुट्टी पर हूँ',
      'manage_absences': 'छुट्टियाँ प्रबंधित करें',
      'add_absence': 'छुट्टी जोड़ें',
      'absence_single_day': 'एक दिन',
      'absence_range': 'तारीख रेंज',
      'absence_recurring': 'साप्ताहिक छुट्टी',
      'select_day_of_week': 'सप्ताह का दिन',
      'monday': 'सोमवार',
      'tuesday': 'मंगलवार',
      'wednesday': 'बुधवार',
      'thursday': 'गुरुवार',
      'friday': 'शुक्रवार',
      'saturday': 'शनिवार',
      'sunday': 'रविवार',
      'no_absences': 'कोई छुट्टी निर्धारित नहीं है।',
      'remove': 'हटाएँ',
      'confirm_broadcast': 'ग्राहकों को सूचित करें?',
      'broadcast_explainer':
          'ऐप ग्राहकों को "कोई डिलीवरी नहीं" अपने आप दिखेगा। बिना ऐप वाले ग्राहकों को WhatsApp भेजने के लिए नीचे टैप करें।',
      'broadcast_via_whatsapp': 'सबको WhatsApp पर सूचित करें',
      'skip_notifications': 'सूचना न भेजें',
      'no_delivery_today': 'आज डिलीवरी नहीं — दूधवाला छुट्टी पर',
      'no_delivery_explainer':
          'आपका दूधवाला आज छुट्टी पर है। आज डिलीवरी नहीं होगी और बिल भी नहीं लगेगा।',
      'absence_added': 'छुट्टी सेव हो गई',
      'every_week_on': 'हर',
      'days_milkman_absent': 'दूधवाला छुट्टी (दिन)',
      'days_subscriber_paused': 'ग्राहक पॉज़ (दिन)',
      'days_delivered_label': 'डिलीवर्ड (दिन)',
      'absent_today_banner_explainer':
          'ग्राहकों को "आज डिलीवरी नहीं" दिखेगा और इन दिनों का बिल नहीं बनेगा।',
      'undo_off_today': 'पूर्ववत करें',
      'absence_reason_hint': 'कारण (वैकल्पिक — त्यौहार, बीमारी, आदि)',
      'today_label': 'आज',
      'yesterday_label': 'कल',
      'no_deliveries_today': 'आज कोई डिलीवरी नहीं है।',
      'qty_label': 'मात्रा',
      'mark_all_done': 'सब डिफ़ॉल्ट मार्क करें',
      'old': 'पुराना',
      'new': 'नया',
      'by': 'द्वारा',
    },
  };

  String t(String key) => _strings[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const ['en', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocExt on BuildContext {
  String tr(String key) => AppLocalizations.of(this).t(key);
}
