import 'package:flutter/material.dart';

/// Hand-rolled localization (no codegen) for English + Hindi.
class AppLocalizations {
  AppLocalizations(this.locale);
  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const _strings = <String, Map<String, String>>{
    'en': {
      'app_title': 'Milk Delivery',
      'login_title': 'Sign in',
      'phone_hint': 'Phone number',
      'send_otp': 'Send OTP',
      'otp_hint': 'Enter OTP (123456)',
      'verify': 'Verify',
      'select_role': 'Continue as',
      'role_milkman': 'Milkman',
      'role_subscriber': 'Subscriber',
      'name_hint': 'Your name',
      'milkman_home': 'Today\'s Route',
      'societies': 'Societies',
      'inbox': 'Inbox',
      'billing': 'Billing',
      'add_society': 'Add Society',
      'society_name': 'Society name',
      'society_address': 'Address',
      'add_flat': 'Add Flat',
      'flat_number': 'Flat number',
      'owner_name': 'Owner name',
      'owner_phone': 'Owner phone',
      'has_app': 'Subscriber has the app',
      'default_quantity': 'Default daily quantity (L)',
      'price_per_litre': 'Price per litre',
      'delivered': 'Delivered',
      'skipped': 'Skipped',
      'paused': 'Paused',
      'custom': 'Custom',
      'mark_delivered': 'Mark Delivered',
      'mark_custom': 'Custom Qty',
      'mark_skipped': 'Skip',
      'change_qty_dialog': 'Quantity (litres)',
      'reason_optional': 'Reason (optional)',
      'save': 'Save',
      'cancel': 'Cancel',
      'whatsapp_notify': 'Notify via WhatsApp',
      'change_requests': 'Change Requests',
      'no_requests': 'No pending requests.',
      'apply': 'Apply',
      'subscriber_today': 'Today',
      'subscriber_history': 'History',
      'subscriber_bill': 'My Bill',
      'pause_today': 'Pause today',
      'pause_tomorrow': 'Pause tomorrow',
      'pause_range': 'Pause date range',
      'change_quantity': 'Change quantity',
      'litres': 'L',
      'total_litres': 'Total litres',
      'total_amount': 'Total amount',
      'days_skipped': 'Days skipped',
      'days_custom': 'Days with custom qty',
      'export_pdf': 'Export PDF',
      'share': 'Share',
      'audit_log': 'Audit log',
      'no_flats': 'No flats yet. Tap + to add one.',
      'no_societies': 'No societies yet. Tap + to add one.',
      'logout': 'Logout',
      'language': 'Language',
      'pending': 'Pending',
      'applied': 'Applied',
      'pause': 'Pause',
      'quantity_change': 'Quantity change',
      'from': 'From',
      'to': 'To',
      'select_dates': 'Select dates',
      'request_submitted': 'Request submitted',
      'no_history': 'No deliveries yet.',
      'monthly_summary': 'Monthly Summary',
      'flat_detail': 'Flat detail',
      'logged_in_as': 'Signed in as',
      'unlinked_subscriber': 'No flat is registered for your phone yet.',
      'unlinked_explainer':
          'Your milkman needs to add a flat with this phone number as the owner. Share the number below with them, then sign back in.',
      'your_phone': 'Your phone',
      'copy': 'Copy',
      'copied': 'Copied to clipboard',
      'try_demo': 'Or try a demo account',
      'demo_subscriber_hint':
          'Sign out and sign in with 9111111111 or 9222222222 (OTP 123456) — both have flats already linked.',
      'milkman_absent': 'Milkman absent',
      'milkman_off_today': 'You\'re off today',
      'im_off_today': 'I\'m off today',
      'manage_absences': 'Manage absences',
      'add_absence': 'Add absence',
      'absence_single_day': 'Single day',
      'absence_range': 'Date range',
      'absence_recurring': 'Weekly off',
      'select_day_of_week': 'Day of the week',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'no_absences': 'No absences scheduled.',
      'remove': 'Remove',
      'confirm_broadcast': 'Notify subscribers?',
      'broadcast_explainer':
          'App subscribers will see "no delivery" automatically. Tap below to send WhatsApp messages to subscribers without the app.',
      'broadcast_via_whatsapp': 'Notify all via WhatsApp',
      'skip_notifications': 'Skip notifications',
      'no_delivery_today': 'No delivery today — milkman off',
      'no_delivery_explainer':
          'Your milkman is off today. There will be no delivery and you won\'t be charged.',
      'absence_added': 'Absence saved',
      'every_week_on': 'Every',
      'days_milkman_absent': 'Days milkman absent',
      'days_subscriber_paused': 'Days subscriber paused',
      'days_delivered_label': 'Days delivered',
      'absent_today_banner_explainer':
          'Subscribers will see "no delivery today" and these dates won\'t be billed.',
      'undo_off_today': 'Undo',
      'absence_reason_hint': 'Reason (optional, e.g. festival, sick)',
      'today_label': 'Today',
      'yesterday_label': 'Yesterday',
      'no_deliveries_today': 'No deliveries scheduled for today.',
      'qty_label': 'Qty',
      'mark_all_done': 'Mark all default',
      'old': 'Old',
      'new': 'New',
      'by': 'By',
      'record_qty_change': 'Note quantity change',
      'change_recorded': 'Change noted',
      'flat_status_active': 'Active',
      'flat_status_paused': 'Paused',
      'flat_status_stopped': 'Stopped',
      'pause_flat': 'Pause deliveries',
      'pause_flat_confirm': 'Pause',
      'resume_flat': 'Resume deliveries',
      'resume_flat_confirm': 'Resume',
      'stop_flat': 'Stop permanently',
      'stop_flat_confirm': 'Stop',
      'edit_flat': 'Edit flat',
      'flat_updated': 'Flat updated',
      'flat_paused': 'Deliveries paused',
      'flat_resumed': 'Deliveries resumed',
      'flat_stopped': 'Flat stopped',
      'stopped_flats': 'Stopped Flats',
      'no_audit': 'No audit entries yet.',
      'catalog': 'Catalog',
      'manage_products': 'Manage products',
      'manage_categories': 'Manage categories',
      'products': 'Products',
      'categories': 'Categories',
      'add_product': 'Add product',
      'edit_product': 'Edit product',
      'add_category': 'Add category',
      'edit_category': 'Edit category',
      'product_name': 'Product name',
      'category': 'Category',
      'unit': 'Unit',
      'unit_litre': 'Litre',
      'unit_kg': 'Kilogram',
      'unit_piece': 'Piece',
      'unit_gram': 'Gram',
      'unit_ml': 'Millilitre',
      'default_price': 'Default price',
      'active': 'Active',
      'inactive': 'Inactive',
      'no_products': 'No products. Add one to start.',
      'no_categories': 'No categories. Add one first.',
      'subscriptions': 'Subscriptions',
      'manage_subscriptions': 'Manage subscriptions',
      'add_subscription': 'Add subscription',
      'no_subscriptions': 'No subscriptions yet for this flat.',
      'product_added': 'Product added',
      'product_updated': 'Product updated',
      'product_deleted': 'Product deleted',
      'category_added': 'Category added',
      'category_updated': 'Category updated',
      'subscription_added': 'Subscription added',
      'subscription_updated': 'Subscription updated',
      'subscription_removed': 'Subscription removed',
      'qty': 'Qty',
      'unit_price': 'Unit price',
      'billing_mode': 'Billing mode',
      'billing_prepaid': 'Prepaid (wallet)',
      'billing_postpaid': 'Postpaid (monthly bill)',
      'wallet': 'Wallet',
      'wallet_balance': 'Wallet balance',
      'wallet_topup': 'Top up wallet',
      'wallet_refund': 'Refund',
      'wallet_history': 'Wallet history',
      'amount': 'Amount',
      'topup_amount': 'Top-up amount',
      'topup_added': 'Top-up added',
      'low_balance': 'Low balance',
      'insufficient_balance': 'Insufficient wallet balance',
      'no_wallet_txns': 'No wallet transactions yet.',
      'debit': 'Debit',
      'credit': 'Credit',
      'auto_debit_delivery': 'Auto-debit for delivery',
      'subtotal': 'Subtotal',
      'per_product_breakdown': 'Per-product breakdown',
      'no_subscriptions_short': 'No subscriptions',
      'mark_all_delivered': 'Mark all delivered',
      'stop_subscription': 'Stop subscription',
      'reactivate_subscription': 'Reactivate',
      'subscription_active': 'Active',
      'subscription_stopped': 'Stopped',
      'todays_items': "Today's items",
      'standalone_customers': 'Standalone Customers',
      'standalone_explainer': 'Houses & shops not in any society',
      'no_standalone_customers': 'No standalone customers yet.',
      'add_customer': 'Add customer',
      'customer_label': 'Customer label',
      'customer_label_hint': 'e.g. House 42, Sharma Stores',
      'address': 'Address',
      'address_optional': 'Address (optional)',
      'address_hint': 'Sector 7, MG Road, near park',
      'customers': 'customers',
      'upi_settings': 'UPI payments',
      'upi_setting_subtitle': 'Let customers pay you via UPI',
      'upi_id': 'Your UPI ID',
      'upi_payee_name': 'Your name (shown in UPI app)',
      'upi_explainer':
          'Enter your UPI ID. Customers will see a "Pay" button on their bill that opens GPay / PhonePe pre-filled with the amount.',
      'invalid_upi': 'Enter a valid UPI ID (e.g. name@oksbi)',
      'saved': 'Saved',
      'clear': 'Clear',
      'pay_via_upi': 'Pay via UPI',
      'topup_via_upi': 'Top up via UPI',
      'upi_not_configured': 'Milkman has not set up UPI yet.',
      'pay_to_upi_id': 'Pay to UPI ID:',
      'search_hint': 'Search by name, flat, phone, address',
      'no_search_results': 'No customers match this search.',
      'collect_payment': 'Collect payment',
      'payment_method': 'Payment method',
      'cash': 'Cash',
      'upi': 'UPI',
      'bank': 'Bank',
      'note_optional': 'Note (optional)',
      'payment_recorded': 'Payment recorded',
      'deliver_with_photo': 'Deliver + capture photo proof',
      'photo_proof_saved': 'Delivered with photo',
    },
    'hi': {
      'app_title': 'दूध डिलीवरी',
      'login_title': 'साइन इन करें',
      'phone_hint': 'फ़ोन नंबर',
      'send_otp': 'OTP भेजें',
      'otp_hint': 'OTP दर्ज करें (123456)',
      'verify': 'सत्यापित करें',
      'select_role': 'जारी रखें',
      'role_milkman': 'दूधवाला',
      'role_subscriber': 'ग्राहक',
      'name_hint': 'आपका नाम',
      'milkman_home': 'आज का रूट',
      'societies': 'सोसाइटी',
      'inbox': 'इनबॉक्स',
      'billing': 'बिल',
      'add_society': 'सोसाइटी जोड़ें',
      'society_name': 'सोसाइटी का नाम',
      'society_address': 'पता',
      'add_flat': 'फ्लैट जोड़ें',
      'flat_number': 'फ्लैट नंबर',
      'owner_name': 'मालिक का नाम',
      'owner_phone': 'मालिक का फ़ोन',
      'has_app': 'ग्राहक के पास ऐप है',
      'default_quantity': 'रोज़ की डिफ़ॉल्ट मात्रा (लीटर)',
      'price_per_litre': 'प्रति लीटर मूल्य',
      'delivered': 'डिलीवर हुआ',
      'skipped': 'छोड़ा गया',
      'paused': 'रुका हुआ',
      'custom': 'अलग मात्रा',
      'mark_delivered': 'डिलीवर्ड',
      'mark_custom': 'अलग मात्रा',
      'mark_skipped': 'छोड़ें',
      'change_qty_dialog': 'मात्रा (लीटर)',
      'reason_optional': 'कारण (वैकल्पिक)',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'whatsapp_notify': 'WhatsApp पर सूचित करें',
      'change_requests': 'बदलाव अनुरोध',
      'no_requests': 'कोई अनुरोध नहीं है।',
      'apply': 'लागू करें',
      'subscriber_today': 'आज',
      'subscriber_history': 'इतिहास',
      'subscriber_bill': 'मेरा बिल',
      'pause_today': 'आज रोकें',
      'pause_tomorrow': 'कल रोकें',
      'pause_range': 'तारीख़ रेंज में रोकें',
      'change_quantity': 'मात्रा बदलें',
      'litres': 'ली',
      'total_litres': 'कुल लीटर',
      'total_amount': 'कुल राशि',
      'days_skipped': 'छोड़े गए दिन',
      'days_custom': 'अलग मात्रा वाले दिन',
      'export_pdf': 'PDF एक्सपोर्ट',
      'share': 'शेयर',
      'audit_log': 'ऑडिट लॉग',
      'no_flats': 'अभी कोई फ्लैट नहीं। + दबाकर जोड़ें।',
      'no_societies': 'अभी कोई सोसाइटी नहीं। + दबाकर जोड़ें।',
      'logout': 'लॉगआउट',
      'language': 'भाषा',
      'pending': 'लंबित',
      'applied': 'लागू',
      'pause': 'रोकें',
      'quantity_change': 'मात्रा बदलाव',
      'from': 'से',
      'to': 'तक',
      'select_dates': 'तारीख़ चुनें',
      'request_submitted': 'अनुरोध भेजा गया',
      'no_history': 'अभी कोई डिलीवरी नहीं।',
      'monthly_summary': 'महीने का सारांश',
      'flat_detail': 'फ्लैट विवरण',
      'logged_in_as': 'साइन इन',
      'unlinked_subscriber': 'इस नंबर पर अभी कोई फ्लैट रजिस्टर नहीं है।',
      'unlinked_explainer':
          'आपके दूधवाले को इस फ़ोन नंबर के मालिक के रूप में फ्लैट जोड़ना होगा। नीचे का नंबर उन्हें दें, फिर दोबारा साइन इन करें।',
      'your_phone': 'आपका फ़ोन',
      'copy': 'कॉपी करें',
      'copied': 'क्लिपबोर्ड पर कॉपी हो गया',
      'try_demo': 'या डेमो अकाउंट आज़माएँ',
      'demo_subscriber_hint':
          'साइन आउट करके 9111111111 या 9222222222 (OTP 123456) से साइन इन करें — दोनों के फ्लैट पहले से लिंक हैं।',
      'milkman_absent': 'दूधवाला छुट्टी पर',
      'milkman_off_today': 'आज आप छुट्टी पर हैं',
      'im_off_today': 'आज मैं छुट्टी पर हूँ',
      'manage_absences': 'छुट्टियाँ प्रबंधित करें',
      'add_absence': 'छुट्टी जोड़ें',
      'absence_single_day': 'एक दिन',
      'absence_range': 'तारीख रेंज',
      'absence_recurring': 'साप्ताहिक छुट्टी',
      'select_day_of_week': 'सप्ताह का दिन',
      'monday': 'सोमवार',
      'tuesday': 'मंगलवार',
      'wednesday': 'बुधवार',
      'thursday': 'गुरुवार',
      'friday': 'शुक्रवार',
      'saturday': 'शनिवार',
      'sunday': 'रविवार',
      'no_absences': 'कोई छुट्टी निर्धारित नहीं है।',
      'remove': 'हटाएँ',
      'confirm_broadcast': 'ग्राहकों को सूचित करें?',
      'broadcast_explainer':
          'ऐप ग्राहकों को "कोई डिलीवरी नहीं" अपने आप दिखेगा। बिना ऐप वाले ग्राहकों को WhatsApp भेजने के लिए नीचे टैप करें।',
      'broadcast_via_whatsapp': 'सबको WhatsApp पर सूचित करें',
      'skip_notifications': 'सूचना न भेजें',
      'no_delivery_today': 'आज डिलीवरी नहीं — दूधवाला छुट्टी पर',
      'no_delivery_explainer':
          'आपका दूधवाला आज छुट्टी पर है। आज डिलीवरी नहीं होगी और बिल भी नहीं लगेगा।',
      'absence_added': 'छुट्टी सेव हो गई',
      'every_week_on': 'हर',
      'days_milkman_absent': 'दूधवाला छुट्टी (दिन)',
      'days_subscriber_paused': 'ग्राहक पॉज़ (दिन)',
      'days_delivered_label': 'डिलीवर्ड (दिन)',
      'absent_today_banner_explainer':
          'ग्राहकों को "आज डिलीवरी नहीं" दिखेगा और इन दिनों का बिल नहीं बनेगा।',
      'undo_off_today': 'पूर्ववत करें',
      'absence_reason_hint': 'कारण (वैकल्पिक — त्यौहार, बीमारी, आदि)',
      'today_label': 'आज',
      'yesterday_label': 'कल',
      'no_deliveries_today': 'आज कोई डिलीवरी नहीं है।',
      'qty_label': 'मात्रा',
      'mark_all_done': 'सब डिफ़ॉल्ट मार्क करें',
      'old': 'पुराना',
      'new': 'नया',
      'by': 'द्वारा',
      'record_qty_change': 'मात्रा नोट करें',
      'change_recorded': 'नोट हो गया',
      'flat_status_active': 'सक्रिय',
      'flat_status_paused': 'रुका हुआ',
      'flat_status_stopped': 'बंद',
      'pause_flat': 'डिलीवरी रोकें',
      'pause_flat_confirm': 'रोकें',
      'resume_flat': 'डिलीवरी फिर शुरू करें',
      'resume_flat_confirm': 'शुरू करें',
      'stop_flat': 'स्थायी रूप से बंद करें',
      'stop_flat_confirm': 'बंद करें',
      'edit_flat': 'फ्लैट संपादित करें',
      'flat_updated': 'फ्लैट अपडेट हो गया',
      'flat_paused': 'डिलीवरी रुकी',
      'flat_resumed': 'डिलीवरी फिर शुरू',
      'flat_stopped': 'फ्लैट बंद हो गया',
      'stopped_flats': 'बंद फ्लैट',
      'no_audit': 'अभी कोई ऑडिट नहीं।',
      'catalog': 'कैटलॉग',
      'manage_products': 'प्रोडक्ट प्रबंधन',
      'manage_categories': 'श्रेणियाँ प्रबंधित करें',
      'products': 'प्रोडक्ट',
      'categories': 'श्रेणियाँ',
      'add_product': 'प्रोडक्ट जोड़ें',
      'edit_product': 'प्रोडक्ट संपादित करें',
      'add_category': 'श्रेणी जोड़ें',
      'edit_category': 'श्रेणी संपादित करें',
      'product_name': 'प्रोडक्ट का नाम',
      'category': 'श्रेणी',
      'unit': 'इकाई',
      'unit_litre': 'लीटर',
      'unit_kg': 'किलोग्राम',
      'unit_piece': 'पीस',
      'unit_gram': 'ग्राम',
      'unit_ml': 'मिलीलीटर',
      'default_price': 'डिफ़ॉल्ट मूल्य',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'no_products': 'कोई प्रोडक्ट नहीं। एक जोड़ें।',
      'no_categories': 'कोई श्रेणी नहीं। पहले जोड़ें।',
      'subscriptions': 'सब्सक्रिप्शन',
      'manage_subscriptions': 'सब्सक्रिप्शन प्रबंधित करें',
      'add_subscription': 'सब्सक्रिप्शन जोड़ें',
      'no_subscriptions': 'इस फ्लैट के लिए अभी कोई सब्सक्रिप्शन नहीं।',
      'product_added': 'प्रोडक्ट जुड़ गया',
      'product_updated': 'प्रोडक्ट अपडेट हो गया',
      'product_deleted': 'प्रोडक्ट हटाया गया',
      'category_added': 'श्रेणी जुड़ी',
      'category_updated': 'श्रेणी अपडेट हुई',
      'subscription_added': 'सब्सक्रिप्शन जुड़ा',
      'subscription_updated': 'सब्सक्रिप्शन अपडेट हुआ',
      'subscription_removed': 'सब्सक्रिप्शन हटाया गया',
      'qty': 'मात्रा',
      'unit_price': 'प्रति यूनिट मूल्य',
      'billing_mode': 'बिलिंग मोड',
      'billing_prepaid': 'प्रीपेड (वॉलेट)',
      'billing_postpaid': 'पोस्टपेड (मासिक बिल)',
      'wallet': 'वॉलेट',
      'wallet_balance': 'वॉलेट बैलेंस',
      'wallet_topup': 'वॉलेट टॉप-अप',
      'wallet_refund': 'रिफंड',
      'wallet_history': 'वॉलेट इतिहास',
      'amount': 'राशि',
      'topup_amount': 'टॉप-अप राशि',
      'topup_added': 'टॉप-अप जुड़ गया',
      'low_balance': 'कम बैलेंस',
      'insufficient_balance': 'वॉलेट में पैसे कम हैं',
      'no_wallet_txns': 'अभी कोई वॉलेट लेन-देन नहीं।',
      'debit': 'डेबिट',
      'credit': 'क्रेडिट',
      'auto_debit_delivery': 'डिलीवरी के लिए ऑटो-डेबिट',
      'subtotal': 'उप-योग',
      'per_product_breakdown': 'प्रोडक्ट-वार विवरण',
      'no_subscriptions_short': 'कोई सब्सक्रिप्शन नहीं',
      'mark_all_delivered': 'सब डिलीवर्ड मार्क करें',
      'stop_subscription': 'सब्सक्रिप्शन रोकें',
      'reactivate_subscription': 'फिर शुरू करें',
      'subscription_active': 'सक्रिय',
      'subscription_stopped': 'रुका हुआ',
      'todays_items': 'आज के आइटम',
      'standalone_customers': 'अकेले ग्राहक',
      'standalone_explainer': 'जो ग्राहक किसी सोसाइटी में नहीं हैं',
      'no_standalone_customers': 'अभी कोई अकेला ग्राहक नहीं।',
      'add_customer': 'ग्राहक जोड़ें',
      'customer_label': 'ग्राहक का पहचान',
      'customer_label_hint': 'जैसे House 42, शर्मा स्टोर',
      'address': 'पता',
      'address_optional': 'पता (वैकल्पिक)',
      'address_hint': 'सेक्टर 7, MG रोड, पार्क के पास',
      'customers': 'ग्राहक',
      'upi_settings': 'UPI भुगतान',
      'upi_setting_subtitle': 'ग्राहकों से UPI पर भुगतान लें',
      'upi_id': 'आपकी UPI ID',
      'upi_payee_name': 'आपका नाम (UPI ऐप में दिखेगा)',
      'upi_explainer':
          'अपनी UPI ID दर्ज करें। ग्राहकों को बिल पर "भुगतान करें" बटन दिखेगा जो GPay / PhonePe में राशि के साथ खुलेगा।',
      'invalid_upi': 'सही UPI ID दर्ज करें (जैसे name@oksbi)',
      'saved': 'सेव हो गया',
      'clear': 'मिटाएँ',
      'pay_via_upi': 'UPI से भुगतान करें',
      'topup_via_upi': 'UPI से वॉलेट टॉप-अप',
      'upi_not_configured': 'दूधवाले ने अभी UPI सेट नहीं किया।',
      'pay_to_upi_id': 'इस UPI ID पर भुगतान करें:',
      'search_hint': 'नाम, फ्लैट, फ़ोन, पते से खोजें',
      'no_search_results': 'कोई ग्राहक नहीं मिला।',
      'collect_payment': 'भुगतान लें',
      'payment_method': 'भुगतान का तरीक़ा',
      'cash': 'नक़द',
      'upi': 'UPI',
      'bank': 'बैंक',
      'note_optional': 'टिप्पणी (वैकल्पिक)',
      'payment_recorded': 'भुगतान दर्ज हो गया',
      'deliver_with_photo': 'फोटो के साथ डिलीवर',
      'photo_proof_saved': 'फोटो के साथ डिलीवर हो गया',
    },
  };

  String t(String key) => _strings[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const ['en', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocExt on BuildContext {
  String tr(String key) => AppLocalizations.of(this).t(key);
}
